# Generated by Django 5.2 on 2025-06-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='applications',
            field=models.TextField(blank=True, help_text='Applications principales (une ligne par application)', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='avantages',
            field=models.TextField(blank=True, help_text='Avantages du produit (une ligne par avantage)', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='caracteristiques',
            field=models.TextField(blank=True, help_text='Caractéristiques principales du produit', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='classe',
            field=models.CharField(blank=True, help_text='Classe du ciment, ex: CPJ 35', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='poids',
            field=models.CharField(blank=True, help_text='Poids par sac, ex: 50 kg', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='resistance',
            field=models.CharField(blank=True, help_text='Résistance, ex: ≥ 22.5 MPa', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='temps_prise',
            field=models.CharField(blank=True, help_text='Temps de prise, ex: 2-6 heures', max_length=100, null=True),
        ),
    ]
